 <?php
 $title = 'Agregar usuario nuevo';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('cliente', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nombre'));
 echo '<br>';
 echo $this->formRow($form->get('numero'));
 echo '<br>';
 echo $this->formRow($form->get('tipo'));
 echo '<br>';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();